//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WinWorkBar.rc
//
#define ID_BTN_DEFAULT                  3
#define IDOK2                           3
#define IDC_BTN_REGISTER                10
#define A_IDI_MAIN                      90
#define IDD_WINWORKBAR_DIALOG           102
#define IDS_STATUS_BAR                  102
#define IDC_EDIT_TASK_TEXT              103
#define IDD_TAB_TASKS                   129
#define IDD_TAB_NOTES                   130
#define IDD_TAB_TODAY                   131
#define IDD_EDIT_CATEGORIES             132
#define IDD_CATEGORIES                  133
#define IDR_MAINMENU                    135
#define ID_MENU                         143
#define ID_MENU_HIDE                    144
#define ID_MM_DO_NOT_HIDE               145
#define ID_MM_NEWTASK                   146
#define ID_MM_NEWNOTE                   147
#define ID_MM_FIND                      148
#define ID_MM_HIDE                      150
#define IDI_ICO_FIND                    150
#define ID_MM_SETTINGS                  151
#define IDI_ICO_NOTE                    151
#define ID_MM_ABOUT                     152
#define IDI_ICO_TASK                    152
#define ID_MM_LOCK                      153
#define IDI_ICO_TODAY                   153
#define ID_MM_EXIT                      154
#define ID_VIEW                         155
#define ID_MM_CATEGORIES                156
#define IDB_BITMAP_LOGO                 161
#define IDC_PS_HAND                     162
#define ID_MM_HELP                      163
#define ID_MM_REGISTER                  164
#define ID_MM_HOMEPAGE                  165
#define IDR_TRAYMENU                    166
#define ID_TRAYMENU_NEWTASK             167
#define ID_TRAYMENU_NEWNOTE             168
#define ID_TRAYMENU_ABOUT               169
#define ID__CLOSE                       170
#define ID_TRAYMENU_CLOSE               171
#define ID_TRAYMENU_SETTINGS            172
#define ID_TRAYMENU_SHOWHIDE            173
#define IDD_ABOUTDLG                    174
#define IDB_NEWTASK                     174
#define IDB_NEWNOTE                     175
#define IDB_TRAYMENU_CLOSE              176
#define IDB_TRAYMENU_ABOUT              177
#define IDB_TRAYMENU_SHOWHIDE           178
#define IDB_TRAYMENU_SETTINGS           179
#define ID_MM_EDIT                      180
#define IDI_TBAR_BTN_DELETE             181
#define IDI_TBAR_BTN_EDIT               182
#define IDI_TBAR_BTN_FIND               183
#define IDI_TBAR_BTN_NEW                184
#define IDI_TBAR_BTN_VIEW               185
#define IDD_EDITDLG_NOTE                186
#define IDI_ICO_CATEGORIES              187
#define IDR_ACCTABLE                    188
#define ID_MM_ONTOP                     189
#define IDB_MENUXP                      191
#define IDR_EDITMENU                    192
#define ID_EDM_INSERT_EMAILLINK         193
#define ID_EDM_INSERT_FILELINK          194
#define ID_EDM_INSERT_WWWLINK           195
#define ID__INSERTFOLDERLINK            196
#define ID_EDM_INSERT_DATE              197
#define ID_EDM_INSERT_LONGDATE          198
#define ID_EDM_INSERT_TIME              199
#define ID_EDM_INSERT_DATETIME          200
#define ID__ED                          201
#define ID__COPY                        202
#define ID__PASET                       203
#define ID_VIEW_ALL                     205
#define IDD_EDITDLG_TASK                205
#define ID_VIEW_BYCATEGORIES            206
#define ID_VIEW_BYPROGRESS              207
#define ID_VIEW_BYPRIORITY              208
#define ID_VIEW_BYVISIBILITY            209
#define ID_VIEW_BYADDINGDATE            210
#define ID_VIEW_BYMODIFYDATE            211
#define ID_BYPROGRESS_NOTDONE           212
#define ID_BYPROGRESS_PARTIALLYDONE     213
#define ID_BYPROGRESS_FINISHED          214
#define ID_BYPROGRESS_ALL               215
#define ID_BYPRIORITY_ALL               216
#define ID_BYPRIORITY_IMPORTANT         217
#define ID_BYPRIORITY_DEFAULT           218
#define ID_BYPRIORITY_NOTIMPORTANT      219
#define ID_BYVISIBILITY_ALL             220
#define ID_BYVISIBILITY_THISMONTH       221
#define ID_BYVISIBILITY_THISWEEK        222
#define ID_BYVISIBILITY_YESTERDAY       223
#define ID_BYVISIBILITY_TODAY           224
#define ID_BYADDINGDATE_ALL             225
#define ID_BYADDINGDATE_THISMONTH       226
#define ID_BYADDINGDATE_THISWEEK        227
#define ID_BYADDINGDATE_YESTERDAY       228
#define ID_BYADDINGDATE_TODAY           229
#define ID_BYCHANGINGDATE_ALL           230
#define ID_BYCHANGINGDATE_THISMONTH     231
#define ID_BYCHANGINGDATE_THISWEEK      232
#define ID_BYCHANGINGDATE_YESTERDAY     233
#define ID_BYCHANGINGDATE_TODAY         234
#define ID_BYCATEGORIES_ALL             235
#define ID_VIEW_BYCATEGORIES236         236
#define ID_VIEW_BYCATEGORIES237         237
#define ID_VIEW_BYCATEGORIES239         239
#define ID_VIEW_BYCATEGORIES240         240
#define IDI_ICO_REPEATS                 242
#define IDD_REPEATS                     243
#define IDI_TBAR_BTN_NEW1               243
#define IDI_CFG_TESTSOUND               243
#define IDD_TOOLINFOWINDOW_DIALOG       244
#define IDB_TIPINFOICON                 245
#define IDD_SEARCH                      246
#define ID_MM_VIEWINBROWSER             247
#define IDD_CONFIG                      247
#define ID_MM_SAVEASHTML                248
#define ID_EDM_CALCULATE                249
#define ID_MM_IMPORT                    250
#define ID_MM_EXPORT                    251
#define IDD_IMPORTEXPORT                252
#define IDB_CUTECLOCK_AM                253
#define IDB_CUTECLOCK_LCD               254
#define IDB_CUTECLOCK_LCDSMALL          255
#define IDB_CUTECLOCK_ZODIAC            256
#define IDD_MESSAGE_ONLY_WINDOW         284
#define IDC_LIST_CATEGORY               1000
#define IDC_ED_CATEGORY                 1001
#define IDC_BTN_ADD                     1002
#define IDC_TAB1                        1008
#define IDC_GRP_DATEANDTIME             1009
#define IDC_GRP_CALENDAR                1010
#define IDC_LAB_TIME                    1013
#define IDC_LAB_DATE_FULL               1014
#define IDC_LAB_DAY                     1015
#define IDC_LAB_CAL                     1016
#define IDC_BTN_NOTES_NEW               1018
#define IDC_EDIT_NOTE_BTN_CATEGORIES    1018
#define IDC_BTN_NOTES_EDIT              1019
#define IDC_CHKFROM                     1019
#define IDC_ED_SELECTED                 1020
#define IDC_BTN_NOTES_DELETE            1020
#define IDC_CHKTO                       1020
#define ID_MM_DELETE                    1021
#define IDC_BTN_NOTES_FIND              1021
#define IDC_BTN_NOTES_VIEW              1022
#define IDC_LAB_TASKVIEW                1023
#define ID_BTN_DESELECTALL              1024
#define IDC_GRP1                        1025
#define ID_BTN_EDIT                     1026
#define IDC_LIST_NOTES                  1026
#define ID_BTN_SELECTALL                1027
#define IDC_LIST_TASKS                  1027
#define IDC_BTN_TASKS_NEW               1028
#define IDC_BTN_TASKS_EDIT              1029
#define IDC_BTN_TASKS_DELETE            1030
#define IDC_BTN_TASKS_FIND              1031
#define IDC_BTN_TASKS_VIEW              1032
#define IDC_EDIT_NOTE_TEXT              1033
#define IDC_REDIT                       1033
#define IDC_LAB_APPNAME                 1034
#define IDC_EDIT_NOTE_LAB_CATEGORIES    1034
#define IDC_LAB_COPYRIGHT1              1035
#define IDC_DATEFROM                    1035
#define IDC_LAB_COPYRIGHT2              1036
#define IDC_DATETO                      1036
#define IDC_PIC_LOGO                    1037
#define IDC_INFO_NOTE                   1039
#define IDC_INFO_TASK                   1040
#define IDC_EDIT_TASK_BTN_CATEGORIES    1041
#define IDC_EDIT_TASK_LAB_CATEGORIES    1042
#define IDC_EDIT_TASK_BTN_CATEGORIES2   1043
#define IDC_EDIT_TASK_BTN_REPEATS       1043
#define IDC_DATE_START                  1044
#define IDC_CHK_STOP                    1045
#define IDC_DATE_STOP                   1046
#define IDC_TIME_START                  1047
#define IDC_LAB_START                   1048
#define IDC_COMBO1                      1049
#define IDC_LIST_PRI                    1049
#define IDC_LIST_LANG                   1049
#define IDC_LIST_IE_DATA                1049
#define IDC_LAB_PRI                     1050
#define IDC_LAB_PROGRESS                1051
#define IDC_SLD_PROGRESS                1052
#define IDC_LAB_PRG_INFO                1053
#define IDC_EDIT_TASK_LAB_CATEGORIES2   1054
#define IDC_EDIT_TASK_LAB_REPEATS       1054
#define IDC_BTN_DELETE                  1054
#define IDC_GRP3                        1054
#define IDC_BTN_DELETE_TASK             1055
#define IDC_GRP_TYPE                    1055
#define IDC_WEEKDAYLIST                 1056
#define IDC_GRP_WEEKDAY                 1057
#define IDC_RD_OFF                      1058
#define IDC_RD_DAYS                     1061
#define IDC_RD_MONTHS                   1062
#define IDC_RD_YEARS                    1063
#define IDC_RD_WEEKDAYS                 1064
#define IDC_CHK_DONE                    1068
#define IDC_BTN_TI_SHOW                 1069
#define IDC_BUTTON2                     1070
#define IDC_BTN_TI_FINISH               1070
#define IDC_ED_WITHWORDS                1071
#define IDC_ED_WITHOUTWORDS             1072
#define IDC_LAB1                        1073
#define IDC_LAB2                        1074
#define IDC_LIST1                       1075
#define IDC_FINDLIST                    1075
#define IDC_LAB_STATUS                  1076
#define IDC_LAB_WWW                     1077
#define IDC_ED_HIDEWINDOWAFTER          1077
#define IDC_SPIN_HIDEWINDOWAFTER        1078
#define IDC_ED_REMIND_SHOW_MINUTESBEFORE 1079
#define IDC_SPIN_MINUTESBEFORE          1080
#define IDC_LIST_SOUNDS                 1081
#define IDC_BTN_TESTSOUND               1082
#define IDC_CHK_PCSPEAKER               1083
#define IDC_ED_TASKPUTAWAY              1084
#define IDC_CHK_AUTORUN                 1085
#define IDC_EMAIL_LINK                  1086
#define IDC_GRP2                        1086
#define IDC_GRP4                        1087
#define IDC_GRP5                        1088
#define IDC_LAB_REMIND_SHOW             1089
#define IDC_LAB_REMIND_SOUND            1090
#define IDC_LAB_HIDEWINDOWAFTER         1091
#define IDC_LAB_REMINDSHOW              1092
#define IDC_PROGRESS_IE                 1093
#define IDC_GRP6                        1093
#define IDC_LAB_IE_TITLE                1094
#define IDC_GRP_TASKLATER               1094
#define IDC_SPIN_HIDEWINDOWAFTER2       1095
#define IDC_SPIN_PUTTASKAWAY            1095
#define IDC_LAB_CLOCK                   1096
#define IDC_LAB_TASKPUTAWAY             1096
#define IDC_COMBO2                      1097
#define IDC_LST_CLOCKSTYLE              1097
#define IDC_CHK_SHOWBARONCLICK          1098
#define IDC_LAB_CAL1                    1099
#define IDC_LAB_CAL2                    1100
#define IDC_REG_LINE1                   1101
#define IDC_BTN_TI_PUTAWAY              1101
#define IDC_REG_LINE3                   1102
#define IDC_REG_LINE2                   1103
#define ID_EDM_INSERT_FOLDERLINK        1109
#define IDC_PROFILE_HOTKEY1             1156
#define IDC_PROFILE_HOTKEY2             1157
#define IDC_SETTING_HOTKEY_CHK1         1158
#define IDC_SETTING_HOTKEY_CHK2         1159
#define IDC_PROFILE_MISC_LAB1           1160
#define IDC_PROFILE_MISC_LAB2           1161
#define IDC_PROFILE_HOTKEY3             1162
#define IDC_SETTING_HOTKEY_CHK3         1163
#define IDC_PROFILE_MISC_LAB3           1164
#define ID_ACC_SAVE                     32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        257
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1102
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
